server:
  port: 8100

spring:
  datasource:
    url: jdbc:h2:file:./h2/parkinglot
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true